### ISSUE TITLE
Issue installing malstroem

### ISSUE THREAD

**Issue by SIGGRUV** [Septima/malstroem#33]
I have previously used the Septima fork of malstroem but need to install it on another computer. I am unable to install it and am uncertain what is happening. This is the text produced in the anaconda prompt:

(malstroem) C:\Users\J>pip install https://github.com/Septima/malstroem/archive/master.zip#[speedups]
Collecting https://github.com/Septima/malstroem/archive/master.zip#[speedups]
  Using cached https://github.com/Septima/malstroem/archive/master.zip
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from malstroem==1.0.0) (1.21.6)
Requirement already satisfied: click in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from malstroem==1.0.0) (8.1.3)
Requirement already satisfied: gdal in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from malstroem==1.0.0) (3.5.2)
Requirement already satisfied: future in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from malstroem==1.0.0) (0.18.2)
Requirement already satisfied: scipy in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from malstroem==1.0.0) (1.7.3)
Requirement already satisfied: click-log==0.1.8 in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from malstroem==1.0.0) (0.1.8)
Requirement already satisfied: colorama in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from click->malstroem==1.0.0) (0.4.6)
Requirement already satisfied: importlib-metadata in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from click->malstroem==1.0.0) (5.0.0)
Requirement already satisfied: zipp>=0.5 in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from importlib-metadata->click->malstroem==1.0.0) (3.10.0)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\users\j\anaconda3\envs\malstroem\lib\site-packages (from importlib-metadata->click->malstroem==1.0.0) (4.4.0)
Building wheels for collected packages: malstroem
  Building wheel for malstroem (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      C:\Users\J\anaconda3\envs\malstroem\lib\site-packages\setuptools\dist.py:774: UserWarning: Usage of dash-separated 'dry-run' will not be supported in future versions. Please use the underscore name 'dry_run' instead
        % (opt, underscore_opt)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\approx.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\bluespots.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\dem.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\hyps.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\io.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\network.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\rain.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\streams.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\vector.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\__init__.py -> build\lib.win-amd64-cpython-37\malstroem
      creating build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\dtypes.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\fill.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\flow.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\label.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\net.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\_raster_utils.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\__init__.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      creating build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\bluespot.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\cli.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\complete.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\dem.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\finalstate.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\hyps.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\initvolume.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\stream.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\_utils.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\__init__.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      creating build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\__init__.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      running egg_info
      creating malstroem.egg-info
      writing malstroem.egg-info\PKG-INFO
      writing dependency_links to malstroem.egg-info\dependency_links.txt
      writing entry points to malstroem.egg-info\entry_points.txt
      writing requirements to malstroem.egg-info\requires.txt
      writing top-level names to malstroem.egg-info\top_level.txt
      writing manifest file 'malstroem.egg-info\SOURCES.txt'
      reading manifest file 'malstroem.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'README.rst'
      adding license file 'LICENSE'
      writing manifest file 'malstroem.egg-info\SOURCES.txt'
      C:\Users\J\anaconda3\envs\malstroem\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'malstroem.algorithms.speedups' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'malstroem.algorithms.speedups' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'malstroem.algorithms.speedups' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'malstroem.algorithms.speedups' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      copying malstroem\algorithms\speedups\_fill.c -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_flow.c -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_label.c -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_definitions.pxd -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_fill.pyx -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_flow.pyx -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_label.pyx -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      running build_ext
      building 'malstroem.algorithms.speedups._fill' extension
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      creating build\temp.win-amd64-cpython-37\Release\malstroem
      creating build\temp.win-amd64-cpython-37\Release\malstroem\algorithms
      creating build\temp.win-amd64-cpython-37\Release\malstroem\algorithms\speedups
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\J\anaconda3\envs\malstroem\lib\site-packages\numpy\core\include -IC:\Users\J\anaconda3\envs\malstroem\include -IC:\Users\J\anaconda3\envs\malstroem\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcmalstroem/algorithms/speedups/_fill.c /Fobuild\temp.win-amd64-cpython-37\Release\malstroem/algorithms/speedups/_fill.obj
      _fill.c
      C:\Users\J\anaconda3\envs\malstroem\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for malstroem
  Running setup.py clean for malstroem
Failed to build malstroem
Installing collected packages: malstroem
  Running setup.py install for malstroem ... error
  error: subprocess-exited-with-error

  × Running setup.py install for malstroem did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      C:\Users\J\anaconda3\envs\malstroem\lib\site-packages\setuptools\dist.py:774: UserWarning: Usage of dash-separated 'dry-run' will not be supported in future versions. Please use the underscore name 'dry_run' instead
        % (opt, underscore_opt)
      running install
      C:\Users\J\anaconda3\envs\malstroem\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\approx.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\bluespots.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\dem.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\hyps.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\io.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\network.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\rain.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\streams.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\vector.py -> build\lib.win-amd64-cpython-37\malstroem
      copying malstroem\__init__.py -> build\lib.win-amd64-cpython-37\malstroem
      creating build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\dtypes.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\fill.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\flow.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\label.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\net.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\_raster_utils.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      copying malstroem\algorithms\__init__.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms
      creating build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\bluespot.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\cli.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\complete.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\dem.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\finalstate.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\hyps.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\initvolume.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\stream.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\_utils.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      copying malstroem\scripts\__init__.py -> build\lib.win-amd64-cpython-37\malstroem\scripts
      creating build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\__init__.py -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      running egg_info
      writing malstroem.egg-info\PKG-INFO
      writing dependency_links to malstroem.egg-info\dependency_links.txt
      writing entry points to malstroem.egg-info\entry_points.txt
      writing requirements to malstroem.egg-info\requires.txt
      writing top-level names to malstroem.egg-info\top_level.txt
      reading manifest file 'malstroem.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'README.rst'
      adding license file 'LICENSE'
      writing manifest file 'malstroem.egg-info\SOURCES.txt'
      C:\Users\J\anaconda3\envs\malstroem\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'malstroem.algorithms.speedups' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'malstroem.algorithms.speedups' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'malstroem.algorithms.speedups' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'malstroem.algorithms.speedups' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      copying malstroem\algorithms\speedups\_fill.c -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_flow.c -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_label.c -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_definitions.pxd -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_fill.pyx -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_flow.pyx -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      copying malstroem\algorithms\speedups\_label.pyx -> build\lib.win-amd64-cpython-37\malstroem\algorithms\speedups
      running build_ext
      building 'malstroem.algorithms.speedups._fill' extension
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      creating build\temp.win-amd64-cpython-37\Release\malstroem
      creating build\temp.win-amd64-cpython-37\Release\malstroem\algorithms
      creating build\temp.win-amd64-cpython-37\Release\malstroem\algorithms\speedups
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\J\anaconda3\envs\malstroem\lib\site-packages\numpy\core\include -IC:\Users\J\anaconda3\envs\malstroem\include -IC:\Users\J\anaconda3\envs\malstroem\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcmalstroem/algorithms/speedups/_fill.c /Fobuild\temp.win-amd64-cpython-37\Release\malstroem/algorithms/speedups/_fill.obj
      _fill.c
      C:\Users\J\anaconda3\envs\malstroem\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> malstroem

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

(malstroem) C:\Users\J>

**Comment by jiaqingxiao** [comment]
me too

**Comment by AsgerPetersen** [comment]
I am sorry. I would love to dive into this, but for the time being I do not have the ressources necessary.

**Comment by AsgerPetersen** [comment]
It turns out that this error is thrown when you try building without having "Windows SDK for Desktop C++" installed. This SO thread https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory explains it.
