### ISSUE TITLE
Projection error message and polygon geometry warning during Malstroem execution

### ISSUE THREAD

**Issue by thomasbalstroem** [Septima/malstroem#34]
Hi Asger,
I get the below errors and warnings when executing the Malstroem module dated Sept. 9 2022.
I hope you can find some time to resolve them.
Best regards,
Thomas

C:\Malstroem>malstroem_20200922 complete -mm 30 -mm 60 -mm 100 -filter "volume > 1" -dem c:\malstroem\inputs\DTM_616_69\DTM_1km_6166_691.tif -outdir c:\Malstroem\Test2 -zresolution 0.10 -vector

ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
Processing
   dem: c:\malstroem\inputs\DTM_616_69\DTM_1km_6166_691.tif
   outdir: c:\Malstroem\Test2
   mm: 100.0mm
   zresolution: 0.1m
   accum: False
   filter: volume > 1
Calculating filled DEM
Calculating bluespot depths
Calculating flow directions
Done
Calculating unfiltered bluespots
Number of bluespots found before filtering: 218412
Calculating filtered bluespots
Number of bluespots left after filtering: 194
Vectorizing bluespots
Warning 1: A geometry of type POLYGON is inserted into layer bluespots of geometry type MULTIPOLYGON, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
Calculating watersheds
Vectorizing watersheds
Warning 1: A geometry of type POLYGON is inserted into layer watersheds of geometry type MULTIPOLYGON, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
Calculating pour points at min filled
Writing 195 pour points
Done
Read input data
Processing stream network
Writing 221 nodes
Reading input nodes
Calculating rain volumes
  100.0mm
Writing output
Done
Reading input nodes
Creating stream network
Calculating final state
Reading initial water volumes from 'inputv'
Writing output
Done
Calculating approximate bluespot water levels using hypsometric histograms
Writing approximate bluespot water levels
Reading approximated water levels
Reading bluespot labels
Setting water levels
Reading DEM
Calculating depths
Writing approximate depths
Writing bluespot labels for approximate extents
Polygonizing final bluespots
0...10...20...30...40...50...60...70...80...90...100 - done.
Complete done...

**Comment by AsgerPetersen** [comment]
This should be fixed in v1.0.1
