### ISSUE TITLE
Python 2.7 deprecation

### ISSUE THREAD

**Issue by phcantis** [Septima/malstroem#6]
Are there plans to migrate / shift this program to python 3.x? With the EOL scheduled for 2020, installation might soon be problematic

**Comment by AsgerPetersen** [comment]
We have no plans at the moment. Mainly because so far no one has offered to fund all or even part of it. I think it is doable within a reasonable amount of time.

**Comment by AsgerPetersen** [comment]
Hi again @phcantis ,
I just realized that malstroem already IS python 3 compatible. As a matter of fact our CI only builds 3.6 and 3.7: https://ci.appveyor.com/project/Septima/malstroem
Regards
Asger
